### ISSUE TITLE
Support for aioredis 2.0

### ISSUE THREAD

**Issue by rra** [kblin/mockaioredis#16]
aioredis 2.0, released on July 30, changes the API in ways that break mockaioredis. The API for creating and shutting down a client is different, the aioredis.errors module no longer exists, and at least some of the command parameters have changed (the `expire` argument to `set` is now `ex`, for instance.)

It looks like mockaioredis will need some changes (I'm not sure how comprehensive) to mock the new version of that library.

**Comment by kblin** [comment]
Thanks for the heads up, I'll take a look at this.

**Comment by kblin** [comment]
Probably a good time to drop `mockredis` for `fakeredis` as well, seeing how the former isn't supported anymore either.

**Comment by kblin** [comment]
Actually, re-reading the `fakeredis` docs, they seem to have some support for aioredis mocking (albeit no aioredis 2 support either), so maybe it's time to just retire this project and point people at `fakeredis` instead.

**Comment by kblin** [comment]
As mentioned last year, I'm retiring this project. Please just use [`fakeredis`](https://github.com/cunla/fakeredis-py), as that's actively developed and supports mocking the sync and async parts of `redis-py` (that now also includes what used to be `aioredis`)
