### ISSUE TITLE
migrate to fakeredis-py?

### ISSUE THREAD

**Issue by jelmer** [kblin/mockaioredis#18]
mockredispy appears to  be dead upstream, and they're recommending fakeredispy as a replacement (https://github.com/cunla/fakeredis-py)

**Comment by garyvdm** [comment]
Hi @jelmer 

P.S. fakeredis-py has a [module](https://github.com/cunla/fakeredis-py#aioredis-2x) that mocks aioredis-2 and redis.asyncio. I've migrated my projects to use that.

**Comment by jelmer** [comment]
Hi Gary!

Oh, neat - that's good to know.
