### ISSUE TITLE
hmget_dict hasn't the expected behaviour

### ISSUE THREAD

**Issue by turbodt** [kblin/mockaioredis#5]
When
```
redis.hmset_dict( 'key', field1='value1', field2='value2')
```
it fails and it shouln't, according to [https://aioredis.readthedocs.io/en/v1.2.0/mixins.html#aioredis.commands.HashCommandsMixin.hmset_dict](docs).

It fails because `hmset_dict(setf, key, *args, **kwargs)` on mockaioredis/comands/hash.py expects `args` to have at least one element. I suggest to change that behaviour.

**Comment by kblin** [comment]
Closed by 9f3135d
